# Configuration for a Dark Forest universe
# Defined in TOML as per https://toml.io/en/v0.5.0

[initializers]
ADMIN_CAN_ADD_PLANETS = true
WORLD_RADIUS_LOCKED = false
TOKEN_MINT_END_TIMESTAMP = 2022-07-07T21:00:00-07:00
TARGET4_RADIUS = 1600
INITIAL_WORLD_RADIUS = 8000

##################################
# SNARK keys & Perlin parameters #
##################################
DISABLE_ZK_CHECKS = true
PLANETHASH_KEY = 430
SPACETYPE_KEY = 431
BIOMEBASE_KEY = 432
PERLIN_MIRROR_X = false
PERLIN_MIRROR_Y = false
PERLIN_LENGTH_SCALE = 16384 # must be a power of two no greater than 16384

######################
# Game configuration #
######################
MAX_NATURAL_PLANET_LEVEL = 256
TIME_FACTOR_HUNDREDTHS = 5000 # speedup/slowdown game
PERLIN_THRESHOLD_1 = 1
PERLIN_THRESHOLD_2 = 2
PERLIN_THRESHOLD_3 = 18
INIT_PERLIN_MIN = 14
INIT_PERLIN_MAX = 15
BIOME_THRESHOLD_1 = 15
BIOME_THRESHOLD_2 = 17
PLANET_RARITY = 16384
PHOTOID_ACTIVATION_DELAY = 14400 # seconds
LOCATION_REVEAL_COOLDOWN = 86400 # seconds
PLANET_TYPE_WEIGHTS = [
  [
    [1, 0, 0, 0, 0],
    [13, 2, 0, 1, 0],
    [13, 2, 0, 1, 0],
    [13, 2, 0, 0, 1],
    [13, 2, 0, 0, 1],
    [13, 2, 0, 0, 1],
    [13, 2, 0, 0, 1],
    [13, 2, 0, 0, 1],
    [13, 2, 0, 0, 1],
    [13, 2, 0, 0, 1],
  ],
  [
    [1, 0, 0, 0, 0],
    [13, 2, 1, 0, 0],
    [12, 2, 1, 1, 0],
    [11, 2, 1, 1, 1],
    [12, 2, 1, 0, 1],
    [12, 2, 1, 0, 1],
    [12, 2, 1, 0, 1],
    [12, 2, 1, 0, 1],
    [12, 2, 1, 0, 1],
    [12, 2, 1, 0, 1],
  ],
  [
    [1, 0, 0, 0, 0],
    [10, 4, 2, 0, 0],
    [10, 4, 1, 1, 0],
    [8, 4, 1, 2, 1],
    [8, 4, 1, 2, 1],
    [8, 4, 1, 2, 1],
    [8, 4, 1, 2, 1],
    [8, 4, 1, 2, 1],
    [8, 4, 1, 2, 1],
    [8, 4, 1, 2, 1],
  ],
  [
    [1, 0, 0, 0, 0],
    [11, 4, 1, 0, 0],
    [11, 4, 1, 0, 0],
    [7, 4, 2, 2, 1],
    [7, 4, 2, 2, 1],
    [7, 4, 2, 2, 1],
    [7, 4, 2, 2, 1],
    [7, 4, 2, 2, 1],
    [7, 4, 2, 2, 1],
    [7, 4, 2, 2, 1],
  ],
]
ARTIFACT_POINT_VALUES = [
  0, 5000, 20000, 240000, 3000000, 20000000
]

##########################
# Planets to add to game #
##########################
