# Configuration for a Dark Forest universe
# Defined in TOML as per https://toml.io/en/v0.5.0

[initializers]
ADMIN_CAN_ADD_PLANETS = true
WORLD_RADIUS_LOCKED = false
TOKEN_MINT_END_TIMESTAMP = 2021-06-06T21:00:00-07:00
TARGET4_RADIUS = 1600
INITIAL_WORLD_RADIUS = 8000

##################################
# SNARK keys & Perlin parameters #
##################################
DISABLE_ZK_CHECKS = false
PLANETHASH_KEY = 420
SPACETYPE_KEY = 421
BIOMEBASE_KEY = 422
PERLIN_MIRROR_X = false
PERLIN_MIRROR_Y = false
PERLIN_LENGTH_SCALE = 16384 # must be a power of two no greater than 16384

######################
# Game configuration #
######################
MAX_NATURAL_PLANET_LEVEL = 256
TIME_FACTOR_HUNDREDTHS = 100 # speedup/slowdown game
PERLIN_THRESHOLD_1 = 14
PERLIN_THRESHOLD_2 = 15
PERLIN_THRESHOLD_3 = 19
INIT_PERLIN_MIN = 13
INIT_PERLIN_MAX = 14
BIOME_THRESHOLD_1 = 15
BIOME_THRESHOLD_2 = 17
PLANET_RARITY = 16384
PHOTOID_ACTIVATION_DELAY = 43200 # seconds
LOCATION_REVEAL_COOLDOWN = 86400 # seconds
PLANET_TYPE_WEIGHTS = [
  [
    [1, 0, 0, 0, 0],
    [13, 2, 0, 1, 0],
    [13, 2, 0, 1, 0],
    [13, 2, 0, 0, 1],
    [13, 2, 0, 0, 1],
    [13, 2, 0, 0, 1],
    [13, 2, 0, 0, 1],
    [13, 2, 0, 0, 1],
    [13, 2, 0, 0, 1],
    [13, 2, 0, 0, 1],
  ],
  [
    [1, 0, 0, 0, 0],
    [13, 2, 1, 0, 0],
    [12, 2, 1, 1, 0],
    [11, 2, 1, 1, 1],
    [12, 2, 1, 0, 1],
    [12, 2, 1, 0, 1],
    [12, 2, 1, 0, 1],
    [12, 2, 1, 0, 1],
    [12, 2, 1, 0, 1],
    [12, 2, 1, 0, 1],
  ],
  [
    [1, 0, 0, 0, 0],
    [11, 4, 1, 0, 0],
    [10, 4, 1, 1, 0],
    [8, 4, 1, 2, 1],
    [8, 4, 1, 2, 1],
    [8, 4, 1, 2, 1],
    [8, 4, 1, 2, 1],
    [8, 4, 1, 2, 1],
    [8, 4, 1, 2, 1],
    [8, 4, 1, 2, 1],
  ],
  [
    [1, 0, 0, 0, 0],
    [11, 4, 1, 0, 0],
    [11, 4, 1, 0, 0],
    [7, 4, 2, 2, 1],
    [7, 4, 2, 2, 1],
    [7, 4, 2, 2, 1],
    [7, 4, 2, 2, 1],
    [7, 4, 2, 2, 1],
    [7, 4, 2, 2, 1],
    [7, 4, 2, 2, 1],
  ],
]

##########################
# Planets to add to game #
##########################
[[planets]]
  x = 0
  y = 0
  level = 5
  planetType = 0
  requireValidLocationId = false
  revealLocation = true

[[planets]]
  x = 500
  y = 0
  level = 4
  planetType = 0
  requireValidLocationId = false
  revealLocation = true

[[planets]]
  x = -500
  y = 0
  level = 4
  planetType = 0
  requireValidLocationId = false
  revealLocation = true

[[planets]]
  x = 0
  y = 700
  level = 4
  planetType = 1
  requireValidLocationId = false
  revealLocation = true

[[planets]]
  x = 0
  y = -700
  level = 4
  planetType = 1
  requireValidLocationId = false
  revealLocation = true

[[planets]]
  x = 400
  y = 300
  level = 3
  planetType = 0
  requireValidLocationId = false
  revealLocation = true

[[planets]]
  x = 200
  y = 300
  level = 3
  planetType = 1
  requireValidLocationId = false
  revealLocation = true

[[planets]]
  x = 400
  y = 800
  level = 3
  planetType = 0
  requireValidLocationId = false
  revealLocation = true

[[planets]]
  x = 660
  y = 640
  level = 3
  planetType = 1
  requireValidLocationId = false
  revealLocation = true

[[planets]]
  x = -400
  y = 300
  level = 3
  planetType = 0
  requireValidLocationId = false
  revealLocation = true

[[planets]]
  x = -200
  y = 300
  level = 3
  planetType = 1
  requireValidLocationId = false
  revealLocation = true

[[planets]]
  x = -400
  y = 800
  level = 3
  planetType = 0
  requireValidLocationId = false
  revealLocation = true

[[planets]]
  x = -660
  y = 640
  level = 3
  planetType = 1
  requireValidLocationId = false
  revealLocation = true

[[planets]]
  x = -400
  y = -300
  level = 3
  planetType = 0
  requireValidLocationId = false
  revealLocation = true

[[planets]]
  x = -200
  y = -300
  level = 3
  planetType = 1
  requireValidLocationId = false
  revealLocation = true

[[planets]]
  x = -400
  y = -800
  level = 3
  planetType = 0
  requireValidLocationId = false
  revealLocation = true

[[planets]]
  x = -660
  y = -640
  level = 3
  planetType = 1
  requireValidLocationId = false
  revealLocation = true

[[planets]]
  x = 400
  y = -300
  level = 3
  planetType = 0
  requireValidLocationId = false
  revealLocation = true

[[planets]]
  x = 200
  y = -300
  level = 3
  planetType = 1
  requireValidLocationId = false
  revealLocation = true

[[planets]]
  x = 400
  y = -800
  level = 3
  planetType = 0
  requireValidLocationId = false
  revealLocation = true

[[planets]]
  x = 660
  y = -640
  level = 3
  planetType = 1
  requireValidLocationId = false
  revealLocation = true
